apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: cd-pipeline
spec:
  params:
    - name: repo-url
      type: string
    - name: branch
      type: string

  tasks:
    - name: clone
      taskRef:
        name: git-clone
      params:
        - name: url
          value: "$(params.repo-url)"
        - name: revision
          value: "$(params.branch)"
      workspaces:
        - name: output
          workspace: pipeline-workspace

    - name: lint
      taskRef:
        name: flake8
      params:
        - name: image
          value: "python:3.9-slim"
        - name: args
          value: ["--count", "--max-complexity=10", "--max-line-length=127", "--statistics"]
      workspaces:
        - name: source
          workspace: pipeline-workspace
      runAfter:
        - clone

  workspaces:
    - name: pipeline-workspace
