apiVersion: tekton.dev/v1beta1 
kind: Task
metadata:
  name: nose
  # Add a description for the task
  annotations:
    description: This task will run nosetests on the provided input.
spec:
  workspaces:
    - name: source
  params:
    - name: args
      type: string
      description: Arguments to pass to nosetests
      default: -v
    - name: database_uri
      type: string
      description: Database URI for tests
      default: sqlite:///test.db
  steps:
    - name: nosetests
      image: python:3.9-slim
      workingDir: $(workspaces.source.path)
      env:
        - name: DATABASE_URI
          value: $(params.d