apiVersion: apps/v1
kind: Deployment
metadata:
  name: accounts
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - name: accounts
        image: IMAGE_NAME_HERE
        ports:
        - containerPort: 8080
