apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: accounts-service
  name: accounts-service
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: accounts-service
  type: NodePort
status:
  loadBalancer: {}
